export interface Trade {
  slug: string;
  name: string;
  plural: string;
  tagline: string;
  intro: string;
  commonJobs: string[];
  licenceNote: string;
}

export interface AusState {
  slug: string;
  abbr: string;
  name: string;
  regulator: string;
  regulatorUrl: string;
  whsAct: string;
  note: string;
}

export interface HrcwCategory {
  slug: string;
  name: string;
  regNum: number;
  whsText: string;
  intro: string;
  keyControls: string[];
  commonTrades: string[];
}

export const TRADES: Trade[] = [
  {
    slug: 'electrician',
    name: 'Electrician',
    plural: 'Electricians',
    tagline: 'Licensed electrical work from residential fit-outs to industrial switchboard upgrades.',
    intro: 'Electrical work is classified as high-risk construction work under WHS Reg 291 whenever it involves energised installations or services. A compliant SWMS must address isolation procedures, test-before-touch protocols, and PPE requirements appropriate to the voltage involved.',
    commonJobs: [
      'Switchboard installation and upgrade',
      'Underground cable laying',
      'Commercial lighting fit-out',
      'Solar PV system connection',
      'Industrial motor control installation',
      'EV charger installation',
    ],
    licenceNote: 'Electrical work in Australia requires a licensed electrical contractor. Licence requirements vary by state but all fall under the relevant Electrical Safety Act.',
  },
  {
    slug: 'plumber',
    name: 'Plumber',
    plural: 'Plumbers',
    tagline: 'Licensed plumbing and gas fitting for residential, commercial, and civil projects.',
    intro: 'Plumbing work often intersects multiple high-risk categories — excavation for underground drainage, work near pressurised gas lines, and confined space entry for tank or pit work. A well-structured SWMS keeps your crew protected and your licence clean.',
    commonJobs: [
      'Hot water system installation',
      'Drainage and sewer connection',
      'Gas fitting and appliance installation',
      'Roof plumbing and guttering',
      'Backflow prevention device installation',
      'Hydrant and sprinkler system work',
    ],
    licenceNote: 'Plumbing and gas fitting requires a licence under each state\'s plumbing legislation. Gas work carries additional certification requirements.',
  },
  {
    slug: 'roofer',
    name: 'Roofer',
    plural: 'Roofers',
    tagline: 'Re-roofing, new roof installation, guttering, fascia, and waterproofing at height.',
    intro: 'Almost every roofing job triggers WHS Reg 291(1)(a) — work involving a fall risk of more than 2 metres. Your SWMS must document edge protection, fall restraint or arrest systems, roof access methods, and fragile roof management before work begins.',
    commonJobs: [
      'Metal roof installation',
      'Tile roof re-bedding and re-pointing',
      'Guttering and downpipe replacement',
      'Skylight installation',
      'Flat roof waterproofing membrane',
      'Fascia and barge board replacement',
    ],
    licenceNote: 'Roofing licence requirements vary by state. Most states require a building or roof plumbing licence for roof work above a certain height or value.',
  },
  {
    slug: 'solar-installer',
    name: 'Solar Installer',
    plural: 'Solar Installers',
    tagline: 'Rooftop solar PV system installation on residential and commercial buildings.',
    intro: 'Solar installation combines two high-risk categories: working at heights on roof surfaces and energised electrical work when connecting to the grid. Your SWMS must cover both the structural roofing phase and the electrical connection phase, often requiring two separate licensed trades.',
    commonJobs: [
      'Residential rooftop solar PV array',
      'Commercial rooftop solar system',
      'Battery storage system installation',
      'EV charger integrated solar system',
      'Ground-mounted solar array',
      'Solar hot water system',
    ],
    licenceNote: 'Solar installation requires a Clean Energy Council accreditation or state equivalent plus an electrical contractor licence for the grid connection work.',
  },
  {
    slug: 'concreter',
    name: 'Concreter',
    plural: 'Concreters',
    tagline: 'Concrete placement, formwork, reinforcement, and finishing for structural and slab work.',
    intro: 'Concrete work spans several high-risk categories depending on the pour — tilt-up and precast panel erection, formwork collapse risk, and excavation for footings. Your SWMS must address concrete placement sequence, formwork propping, and the specific hazards of your structural system.',
    commonJobs: [
      'House slab and footing pour',
      'Driveway and path concrete',
      'Retaining wall construction',
      'Tilt-up panel construction',
      'Staircase construction',
      'Structural column and beam pour',
    ],
    licenceNote: 'Concreting work generally requires a builder\'s licence for structural elements. Tilt-up and precast work has additional WorkSafe guidance in most states.',
  },
  {
    slug: 'carpenter',
    name: 'Carpenter',
    plural: 'Carpenters',
    tagline: 'Framing, fit-out, formwork, decking, and structural timber work.',
    intro: 'Carpentry spans from ground-level fit-out to elevated framing where fall risk is constant. Roof framing, deck construction, and formwork installation all require detailed SWMS documentation covering fall prevention, manual handling of heavy structural members, and power tool safety.',
    commonJobs: [
      'Wall and roof framing',
      'Deck and pergola construction',
      'Internal fit-out and joinery',
      'Formwork installation',
      'Staircase fabrication and installation',
      'Structural steel and timber hybrid frames',
    ],
    licenceNote: 'Carpentry work over certain values requires a builder\'s licence in most states. Formwork for structural concrete has additional competency requirements.',
  },
  {
    slug: 'painter',
    name: 'Painter',
    plural: 'Painters',
    tagline: 'Interior and exterior painting, surface preparation, and protective coatings.',
    intro: 'Painting may look low-risk but frequently involves fall hazards on ladders and scaffolding, chemical exposure from solvent-based coatings, and lead paint disturbance on older buildings. A thorough SWMS addresses each of these alongside client property protection and adequate ventilation.',
    commonJobs: [
      'Residential exterior repaint',
      'Commercial interior repaint',
      'Industrial protective coatings',
      'Heritage building repainting',
      'Roof painting',
      'Line marking and traffic paint',
    ],
    licenceNote: 'Painting licences are required in most states for work above a set contract value. Painters working with or near asbestos require additional training and, in some cases, an asbestos removal licence.',
  },
  {
    slug: 'hvac-technician',
    name: 'HVAC Technician',
    plural: 'HVAC Technicians',
    tagline: 'Air conditioning installation, service, and refrigerant handling for commercial and residential systems.',
    intro: 'HVAC work combines electrical work, work in confined mechanical spaces, refrigerant handling under pressure, and frequent roof access. Your SWMS must cover each hazard category relevant to the specific job — a rooftop commercial unit replacement is very different from a split system install.',
    commonJobs: [
      'Split system installation',
      'Ducted system installation',
      'Rooftop package unit installation',
      'Chiller and cooling tower service',
      'Mechanical plant room service',
      'Refrigerant recovery and recharge',
    ],
    licenceNote: 'HVAC work requires an ARCtick licence for refrigerant handling and an electrical licence for wiring. Some states also require an HVAC contractor licence for installation work.',
  },
  {
    slug: 'bricklayer',
    name: 'Bricklayer',
    plural: 'Bricklayers',
    tagline: 'Bricklaying, blockwork, stone masonry, and associated rendering.',
    intro: 'Bricklaying involves sustained manual handling of heavy masonry units, frequent scaffold use as walls rise, and mortar chemical exposure. For walls above 2 metres, your SWMS must address scaffold erection and inspection requirements, as well as brick and mortar storage on elevated platforms.',
    commonJobs: [
      'External brick veneer construction',
      'Structural double-brick construction',
      'Retaining and boundary walls',
      'Render and bagging',
      'Fireplace and chimney construction',
      'Paving and feature stone walls',
    ],
    licenceNote: 'Bricklaying above certain contract values requires a building licence. Scaffold erection over 4 metres must be performed by a licensed scaffolder in most states.',
  },
  {
    slug: 'tiler',
    name: 'Tiler',
    plural: 'Tilers',
    tagline: 'Wall and floor tiling, waterproofing membranes, and wet area installations.',
    intro: 'Tiling often involves working in confined wet areas, handling adhesives and grouts with significant chemical hazards, and applying waterproofing membranes that require proper respiratory protection. Roof tiling adds fall risk and manual handling of heavy concrete or terracotta tiles.',
    commonJobs: [
      'Bathroom and laundry tiling',
      'External paving and pool surrounds',
      'Roof tile installation',
      'Wet area waterproofing',
      'Commercial kitchen and amenities tiling',
      'Large-format floor tile installation',
    ],
    licenceNote: 'Wall and floor tiling requires a contractor\'s licence in most states. Roof tiling may be covered under a roofing or building licence.',
  },
  {
    slug: 'plasterer',
    name: 'Plasterer',
    plural: 'Plasterers',
    tagline: 'Plastering, rendering, partition wall systems, and ceiling installation.',
    intro: 'Plasterers regularly work at height on internal scaffolding and stilts, handle gypsum and cement compounds with inhalation hazards, and work in confined spaces during renovation projects. External rendering on multi-storey buildings involves scaffolding and fall prevention controls throughout the job.',
    commonJobs: [
      'Internal set plaster finish',
      'External cement render',
      'Cornice and architrave work',
      'Steel stud partition systems',
      'Suspended ceiling installation',
      'Fire-rated wall and ceiling systems',
    ],
    licenceNote: 'Plastering requires a contractor\'s licence in most states. Fire-rated systems may require additional competency certification.',
  },
  {
    slug: 'scaffolder',
    name: 'Scaffolder',
    plural: 'Scaffolders',
    tagline: 'Scaffold erection, modification, and dismantling for construction sites of all sizes.',
    intro: 'Scaffolding work is itself high-risk construction work under WHS Reg 291, combining fall risk during erection with the manual handling of heavy tubes and boards. Your SWMS must address the erection sequence, working at leading edge, inspection requirements, and handover certification.',
    commonJobs: [
      'Tube and coupler scaffold erection',
      'System scaffold (e.g. Kwikstage) installation',
      'Mobile scaffold assembly',
      'Cantilevered scaffold construction',
      'Suspended (swing stage) scaffold',
      'Scaffold modification and dismantling',
    ],
    licenceNote: 'Scaffolding work requires a High Risk Work Licence — Scaffolding class (Basic, Intermediate, or Advanced) depending on the scaffold type and height.',
  },
  {
    slug: 'rigger',
    name: 'Rigger',
    plural: 'Riggers',
    tagline: 'Crane and rigging operations, structural steel erection, and heavy lift coordination.',
    intro: 'Rigging involves the most complex intersection of high-risk construction work categories — powered mobile plant (cranes), falls risk during structural steel connection, manual handling of heavy loads, and close proximity to traffic and live services on some sites. Each lift requires a documented lift study and task-specific SWMS.',
    commonJobs: [
      'Structural steel erection',
      'Precast concrete panel placement',
      'Plant and equipment installation',
      'Crane-assisted roof and facade work',
      'Heavy machinery relocation',
      'Mast climbing and communication tower work',
    ],
    licenceNote: 'Rigging requires a High Risk Work Licence — Rigging class (Basic, Intermediate, Advanced, or Crane Chasing) depending on the work type.',
  },
  {
    slug: 'glazier',
    name: 'Glazier',
    plural: 'Glaziers',
    tagline: 'Glass installation, curtain wall systems, frameless glazing, and glazing replacement.',
    intro: 'Glazing work combines fall risk during elevated glass installation, manual handling of large heavy glass panels, and the inherent laceration hazard of working with glass. Curtain wall and structural glazing on commercial buildings often involves suspended access equipment and complex rigging for panel placement.',
    commonJobs: [
      'Residential window and door glazing',
      'Commercial curtain wall installation',
      'Shopfront and entrance glazing',
      'Frameless pool fencing and balustrade',
      'Overhead and atrium glazing',
      'Glass replacement after breakage',
    ],
    licenceNote: 'Glazing requires a contractor\'s licence in most states. Structural glazing and curtain wall work may require a building licence.',
  },
  {
    slug: 'demolition-contractor',
    name: 'Demolition Contractor',
    plural: 'Demolition Contractors',
    tagline: 'Structural demolition, strip-out, and controlled deconstruction of buildings and structures.',
    intro: 'Demolition is one of the highest-risk construction activities — it triggers multiple WHS Reg 291 categories simultaneously, including structural alteration of load-bearing elements, potential asbestos disturbance, fall risk from exposed edges, and work near energised services. A detailed, job-specific SWMS and a Demolition Work Plan are both required under Australian WHS law.',
    commonJobs: [
      'Full structural demolition',
      'Selective internal strip-out',
      'Asbestos-containing material removal',
      'Chimney and wall demolition',
      'Slab and footing removal',
      'Commercial fit-out demolition',
    ],
    licenceNote: 'Demolition requires a demolition contractor\'s licence in most states. Asbestos removal above 10m² of friable material requires a Class A asbestos removal licence.',
  },
];

export const STATES: AusState[] = [
  {
    slug: 'nsw',
    abbr: 'NSW',
    name: 'New South Wales',
    regulator: 'SafeWork NSW',
    regulatorUrl: 'https://www.safework.nsw.gov.au',
    whsAct: 'Work Health and Safety Act 2011 (NSW)',
    note: 'SafeWork NSW enforces the model WHS Act with minimal variation. Principal contractors on notifiable projects must ensure a WHS Management Plan is in place before a SWMS can be relied upon.',
  },
  {
    slug: 'vic',
    abbr: 'VIC',
    name: 'Victoria',
    regulator: 'WorkSafe Victoria',
    regulatorUrl: 'https://www.worksafe.vic.gov.au',
    whsAct: 'Occupational Health and Safety Act 2004 (VIC)',
    note: 'Victoria operates under the OHS Act 2004 and OHS Regulations 2017 rather than the model WHS Act. The high-risk construction work categories and SWMS requirements mirror the model regulations closely but use OHS terminology throughout.',
  },
  {
    slug: 'qld',
    abbr: 'QLD',
    name: 'Queensland',
    regulator: 'Workplace Health and Safety Queensland',
    regulatorUrl: 'https://www.worksafe.qld.gov.au',
    whsAct: 'Work Health and Safety Act 2011 (QLD)',
    note: 'WHSQ enforces the model WHS Act. Queensland has specific guidance on high-risk construction work through its Safe Work Method Statement requirements and conducts targeted inspections on construction sites statewide.',
  },
  {
    slug: 'wa',
    abbr: 'WA',
    name: 'Western Australia',
    regulator: 'WorkSafe WA',
    regulatorUrl: 'https://www.dmirs.wa.gov.au/worksafe',
    whsAct: 'Work Health and Safety Act 2020 (WA)',
    note: 'Western Australia adopted the model WHS Act in 2020, replacing the Occupational Safety and Health Act 1984. WA aligns closely with the national model regulations, including the SWMS requirements for high-risk construction work.',
  },
  {
    slug: 'sa',
    abbr: 'SA',
    name: 'South Australia',
    regulator: 'SafeWork SA',
    regulatorUrl: 'https://www.safework.sa.gov.au',
    whsAct: 'Work Health and Safety Act 2012 (SA)',
    note: 'SafeWork SA enforces the model WHS Act adopted in 2012. South Australia has additional guidance for construction work through its SafeWork SA website and conducts proactive construction site inspections.',
  },
  {
    slug: 'tas',
    abbr: 'TAS',
    name: 'Tasmania',
    regulator: 'WorkSafe Tasmania',
    regulatorUrl: 'https://worksafe.tas.gov.au',
    whsAct: 'Work Health and Safety Act 2012 (TAS)',
    note: 'WorkSafe Tasmania enforces the model WHS Act. Tasmania adopted the model WHS framework in 2012 and its construction requirements align with the national standard for SWMS and high-risk construction work.',
  },
  {
    slug: 'act',
    abbr: 'ACT',
    name: 'Australian Capital Territory',
    regulator: 'WorkSafe ACT',
    regulatorUrl: 'https://www.worksafe.act.gov.au',
    whsAct: 'Work Health and Safety Act 2011 (ACT)',
    note: 'WorkSafe ACT enforces the model WHS Act. Construction work in the ACT is regulated consistently with the national model, and the ACT Government is often a principal contractor on significant public works requiring SWMS compliance.',
  },
  {
    slug: 'nt',
    abbr: 'NT',
    name: 'Northern Territory',
    regulator: 'NT WorkSafe',
    regulatorUrl: 'https://worksafe.nt.gov.au',
    whsAct: 'Work Health and Safety (National Uniform Legislation) Act 2011 (NT)',
    note: 'NT WorkSafe enforces the model WHS Act. Construction projects in the NT — particularly in remote areas — carry additional logistical hazards around emergency response, remote medical access, and extreme heat that must be addressed in the SWMS.',
  },
];

export const HRCW_CATEGORIES: HrcwCategory[] = [
  {
    slug: 'working-at-heights',
    name: 'Working at Heights',
    regNum: 1,
    whsText: 'Risk of a person falling more than 2 metres',
    intro: 'Work at heights is the single most common high-risk construction category and one of the leading causes of fatal injuries on Australian worksites. Any task where a person could fall more than 2 metres requires a SWMS — including work on roofs, scaffolding, elevated platforms, and near unprotected edges.',
    keyControls: [
      'Install perimeter edge protection or safety mesh before work begins',
      'Use fall restraint or fall arrest systems when edge protection is not practicable',
      'Inspect all elevated work platforms and scaffolding before use each shift',
      'Implement a fall from height rescue plan before commencing work',
      'Prohibit work at heights during adverse weather that affects stability',
    ],
    commonTrades: ['roofer', 'solar-installer', 'scaffolder', 'carpenter', 'painter', 'glazier'],
  },
  {
    slug: 'telecom-towers',
    name: 'Telecommunication Tower Work',
    regNum: 2,
    whsText: 'Work on a telecommunication tower',
    intro: 'Work on telecommunication towers involves extreme heights, exposed structural elements, and often energised antenna systems. This work requires specialist fall protection systems rated for the specific tower type and a detailed emergency rescue plan given the difficulty of rescue at height.',
    keyControls: [
      'Confirm tower owner approval and any site-specific induction requirements',
      'Use a full body harness with twin-leg lanyards rated for the specific anchor points',
      'Implement radio frequency (RF) safety exclusion zones around active antennas',
      'Establish a ground-level safety observer in constant communication with workers aloft',
      'Complete a site-specific emergency rescue plan before ascending',
    ],
    commonTrades: ['rigger', 'electrician'],
  },
  {
    slug: 'demolition',
    name: 'Demolition of Load-Bearing Elements',
    regNum: 3,
    whsText: 'Demolition of an element of a structure that is load-bearing or otherwise related to the physical integrity of the structure',
    intro: 'Demolishing load-bearing structural elements — walls, columns, beams, slabs — creates collapse risk for adjacent structure. This work requires a structural engineer to assess the demolition sequence and temporary propping requirements before any load-bearing element is disturbed.',
    keyControls: [
      'Obtain a structural engineering report on the demolition sequence before commencing',
      'Install temporary propping to adjacent structure as specified by the engineer',
      'Isolate and cap all services (electrical, gas, water) before demolition begins',
      'Establish an exclusion zone around the demolition area sized to the collapse potential',
      'Use a methodical sequential demolition approach — never over-demolish before propping',
    ],
    commonTrades: ['demolition-contractor', 'carpenter', 'concreter'],
  },
  {
    slug: 'asbestos',
    name: 'Asbestos Disturbance',
    regNum: 4,
    whsText: 'Likely to involve disturbing asbestos',
    intro: 'Any work that is likely to disturb asbestos-containing materials (ACM) requires a SWMS and must only be carried out by a licensed asbestos removalist (Class A or B depending on the material). ACM is present in most buildings constructed before 1990 in Australia.',
    keyControls: [
      'Conduct an asbestos survey before any demolition, renovation, or drilling in pre-1990 buildings',
      'Engage a licensed asbestos assessor to identify, test, and scope ACM removal',
      'Class B licence required for bonded ACM removal; Class A for friable ACM',
      'Establish a regulated asbestos removal area with air monitoring and decontamination',
      'Dispose of ACM only at an approved facility in double-bagged, labelled waste',
    ],
    commonTrades: ['demolition-contractor', 'plumber', 'electrician', 'carpenter'],
  },
  {
    slug: 'structural-alterations',
    name: 'Structural Alterations Requiring Temporary Support',
    regNum: 5,
    whsText: 'Structural alterations or repairs that require temporary support to prevent collapse',
    intro: 'Structural alterations — including opening walls for windows or doors, removing beams, or repairing damaged structural elements — require temporary propping to prevent unintended collapse. The temporary support design must be assessed by a competent person, typically a structural engineer.',
    keyControls: [
      'Obtain a propping design from a structural engineer for any load redistribution',
      'Install temporary propping before cutting or removing any structural element',
      'Inspect propping for settlement or movement before and during the work',
      'Restrict access to the propped area to authorised personnel only',
      'Do not remove temporary supports until permanent structure is certified as capable of carrying load',
    ],
    commonTrades: ['carpenter', 'concreter', 'demolition-contractor', 'bricklayer'],
  },
  {
    slug: 'confined-spaces',
    name: 'Confined Space Work',
    regNum: 6,
    whsText: 'Work in or near a confined space',
    intro: 'Confined spaces — pits, tanks, culverts, ducts, vaults, and similar enclosed areas — present risk of oxygen deficiency, toxic or flammable atmosphere, and engulfment. Entry into a confined space requires atmospheric testing, a confined space entry permit, and a trained standby person with rescue capability.',
    keyControls: [
      'Test atmosphere (oxygen, flammable gas, toxic gas) before and continuously during entry',
      'Issue a confined space entry permit signed by the principal contractor representative',
      'Maintain continuous communication between entrant and standby person',
      'Station a trained confined space rescue team before first entry',
      'Provide continuous mechanical ventilation unless atmospheric testing confirms safety',
    ],
    commonTrades: ['plumber', 'electrician', 'hvac-technician', 'painter'],
  },
  {
    slug: 'excavation',
    name: 'Excavation and Trenching',
    regNum: 7,
    whsText: 'Work in or near a shaft or trench that is more than 1.5 metres deep, or a tunnel',
    intro: 'Trenches and shafts deeper than 1.5 metres can collapse without warning, burying workers under tonnes of spoil. Excavation support — battering, benching, or shoring — must be installed based on a geotechnical assessment of the soil type and ground conditions.',
    keyControls: [
      'Dial Before You Dig (1100) to identify and locate underground services before excavating',
      'Install appropriate trench support (sheet piling, hydraulic shoring, or battering) for depths >1.5m',
      'Inspect trench support before each shift and after rain or other events',
      'Prohibit worker entry without trench support in place and inspected',
      'Prohibit plant operation within the zone of influence of the trench edge',
    ],
    commonTrades: ['plumber', 'electrician', 'concreter'],
  },
  {
    slug: 'explosives',
    name: 'Explosives Use',
    regNum: 8,
    whsText: 'Work involving the use of explosives',
    intro: 'The use of explosives on construction sites — for demolition, rock breaking, or ground preparation — is strictly licensed and requires a site-specific blasting plan, exclusion zones, and coordination with emergency services. Only licensed shot-firers may handle and detonate explosives.',
    keyControls: [
      'Only a licensed shot-firer may handle, transport, and detonate explosives',
      'Submit a blasting plan to the relevant authority and notify emergency services',
      'Establish and enforce a minimum exclusion zone per the blasting plan',
      'Implement misfire procedures — never re-enter the blast area without shot-firer clearance',
      'Store explosives in approved magazines separated from detonators',
    ],
    commonTrades: ['demolition-contractor'],
  },
  {
    slug: 'pressurised-gas',
    name: 'Pressurised Gas Line Work',
    regNum: 9,
    whsText: 'Work on or near pressurised gas distribution mains or piping',
    intro: 'Work near gas distribution mains carries risk of uncontrolled gas release, fire, and explosion. Only licensed gas fitters may work directly on gas installations, and any work near distribution mains must be coordinated with the network operator who controls isolation and purging.',
    keyControls: [
      'Contact the gas network operator before any excavation or work near gas mains',
      'Obtain a gas isolation certificate before cutting into any gas piping',
      'Ensure continuous atmospheric gas monitoring in work areas near gas lines',
      'Have gas detection equipment and emergency response plan ready before commencing',
      'Only licensed gas fitters to perform work on or near gas installations',
    ],
    commonTrades: ['plumber', 'hvac-technician', 'demolition-contractor'],
  },
  {
    slug: 'chemical-fuel-lines',
    name: 'Chemical, Fuel, or Refrigerant Line Work',
    regNum: 10,
    whsText: 'Work on or near chemical, fuel or refrigerant lines',
    intro: 'Work near chemical, fuel, or refrigerant pipework involves risk of exposure to hazardous substances, fire, and environmental harm. Refrigerant recovery must be performed by ARCtick-licensed technicians, and fuel line work requires isolation, purging, and atmospheric testing before hot work is permitted.',
    keyControls: [
      'Obtain Safety Data Sheets (SDS) for all chemicals, fuels, or refrigerants involved',
      'Isolate and depressurise lines before cutting or connecting',
      'Recover refrigerant with ARCtick-licensed equipment — never vent to atmosphere',
      'Prohibit ignition sources in the work area during fuel or refrigerant handling',
      'Ensure PPE matches the chemical hazard in the SDS',
    ],
    commonTrades: ['hvac-technician', 'plumber', 'demolition-contractor'],
  },
  {
    slug: 'energised-electrical',
    name: 'Energised Electrical Work',
    regNum: 11,
    whsText: 'Work on or near energised electrical installations or services',
    intro: 'Work on or near energised electrical installations is one of the most commonly triggered high-risk categories for tradies. Electrical isolation, lock-out/tag-out, and test-before-touch are non-negotiable safety steps before any electrical work begins. Only licensed electrical workers may perform electrical work.',
    keyControls: [
      'Apply Lock-Out/Tag-Out (LOTO) to all isolation points before beginning work',
      'Test-Before-Touch using an approved voltage tester at the work point — not just at the board',
      'Only a licensed electrical worker may perform or supervise electrical work',
      'Establish an exclusion zone around any energised equipment that cannot be isolated',
      'Document all isolation points in a permit-to-work or SWMS before work starts',
    ],
    commonTrades: ['electrician', 'solar-installer', 'hvac-technician'],
  },
  {
    slug: 'contaminated-atmosphere',
    name: 'Contaminated or Flammable Atmosphere',
    regNum: 12,
    whsText: 'Work in an area that may have a contaminated or flammable atmosphere',
    intro: 'Sites with potentially contaminated or flammable atmospheres — including fuel storage facilities, chemical plants, sewer environments, and sites with residual solvent vapour — require atmospheric testing before entry and continuous monitoring during work. Hot work (welding, grinding, cutting) must never proceed without gas clearance.',
    keyControls: [
      'Test atmosphere for flammable gas, oxygen level, and toxic substances before entry',
      'Issue a hot work permit only after gas-free clearance from a gas tester',
      'Maintain continuous forced ventilation throughout work in a contaminated area',
      'Keep fire extinguisher appropriate to the hazard type immediately adjacent to the work',
      'Establish an emergency evacuation signal and muster point before commencing',
    ],
    commonTrades: ['plumber', 'painter', 'demolition-contractor', 'hvac-technician'],
  },
  {
    slug: 'tilt-up-concrete',
    name: 'Tilt-Up and Precast Concrete',
    regNum: 13,
    whsText: 'Tilt-up or precast concrete work',
    intro: 'Tilt-up and precast panel construction involves lifting large concrete elements with cranes and positioning them on foundation ledges. Panel collapse during erection or before permanent bracing is installed is the critical hazard. All lift rigging must be engineered and certified, and temporary bracing must be designed for the panel size and wind load.',
    keyControls: [
      'Obtain an engineered lift study and rigging design for every panel lift',
      'Install temporary bracing immediately after the panel is positioned — before releasing crane hooks',
      'Establish an exclusion zone beneath the lift path and around the erection area',
      'Ensure only qualified riggers and crane operators perform tilt-up operations',
      'Inspect panel inserts, lifting anchors, and rigging hardware before each lift',
    ],
    commonTrades: ['concreter', 'rigger'],
  },
  {
    slug: 'traffic-management',
    name: 'Traffic Management',
    regNum: 14,
    whsText: 'Work on, in or adjacent to a road, railway, shipping lane or other traffic corridor in use by vehicles or vessels',
    intro: 'Work adjacent to live traffic is one of the most hazardous environments for construction workers. Being struck by a vehicle or plant is a leading cause of fatalities. A Traffic Management Plan (TMP) developed to Austroads and state-specific standards must be in place before work commences.',
    keyControls: [
      'Develop a Traffic Management Plan (TMP) to Austroads Guide to Traffic Management standards',
      'Obtain all required road occupancy permits from the road authority',
      'Engage accredited traffic controllers to manage traffic during work hours',
      'Install physical separation (barriers, delineators, cones) between workers and traffic',
      'Brief all workers on the TMP, emergency vehicle procedures, and evacuation routes',
    ],
    commonTrades: ['concreter', 'painter', 'plumber', 'electrician'],
  },
  {
    slug: 'mobile-plant',
    name: 'Powered Mobile Plant',
    regNum: 15,
    whsText: 'Work in an area where there is any movement of powered mobile plant',
    intro: 'Interaction between workers on foot and powered mobile plant — excavators, forklifts, skid steers, concrete trucks — is a leading cause of serious construction injuries. Segregation of pedestrians and plant through physical barriers, spotter arrangements, and site traffic management is essential.',
    keyControls: [
      'Physically separate pedestrian zones from plant operating areas using barriers or exclusion zones',
      'Assign a dedicated spotter when plant is reversing or operating with limited visibility',
      'Ensure all plant operators hold a valid High Risk Work Licence for the class of plant',
      'Establish a site-specific plant and pedestrian traffic management plan',
      'Conduct pre-start checks on all plant before operation each shift',
    ],
    commonTrades: ['concreter', 'demolition-contractor', 'rigger', 'bricklayer'],
  },
  {
    slug: 'extreme-temperatures',
    name: 'Extreme Temperature Work',
    regNum: 16,
    whsText: 'Work in areas with artificial extremes of temperature',
    intro: 'Work in cold rooms, furnace environments, hot water plant rooms, or outdoor environments with extreme heat or cold presents risk of heat stress, hypothermia, and heat-related illness. The SWMS must document temperature monitoring, rest and hydration requirements, and acclimatisation procedures.',
    keyControls: [
      'Monitor ambient temperature and wet bulb globe temperature (WBGT) at the work area',
      'Implement rest and shade requirements as per the relevant heat stress standard',
      'Provide cold water and electrolyte drinks during hot work; warm drinks and dry shelters in cold',
      'Train workers to recognise early signs of heat exhaustion, heat stroke, and hypothermia',
      'Schedule hot outdoor work for cooler parts of the day where practicable',
    ],
    commonTrades: ['hvac-technician', 'painter', 'demolition-contractor'],
  },
  {
    slug: 'work-near-water',
    name: 'Work Near Water — Drowning Risk',
    regNum: 17,
    whsText: 'Work in or near water or other liquid that involves a risk of drowning',
    intro: 'Construction work near open water, stormwater systems, swimming pools under construction, or flooded excavations presents a drowning risk that must be specifically addressed in the SWMS. Rescue equipment and emergency response must be planned before work begins.',
    keyControls: [
      'Identify and mark all open water hazards before commencing work on site',
      'Station water rescue equipment (throw bags, ring buoys, reach poles) within 30 seconds of the water hazard',
      'Require life jackets or personal flotation devices for work over or immediately adjacent to water',
      'Establish a rescue and resuscitation plan — ensure at least one worker per crew holds current first aid including drowning response',
      'Fence or cover all excavations adjacent to water that could be flooded',
    ],
    commonTrades: ['plumber', 'concreter', 'painter'],
  },
  {
    slug: 'diving-work',
    name: 'Diving Work',
    regNum: 18,
    whsText: 'Diving work',
    intro: 'Underwater construction and inspection work requires specialist diving contractors operating under a dive plan with surface support and emergency decompression provisions. Only licensed commercial divers may perform construction diving in Australia.',
    keyControls: [
      'Engage only licensed commercial divers with current dive medicals',
      'Prepare a site-specific dive plan detailing maximum depth, gas mix, bottom time, and ascent rates',
      'Station a trained dive supervisor and safety diver on the surface throughout all underwater operations',
      'Ensure emergency decompression and oxygen therapy equipment is immediately available',
      'Coordinate with relevant harbour master or waterway authority before commencing diving operations',
    ],
    commonTrades: ['plumber'],
  },
];

export function getTradeBySlug(slug: string): Trade | undefined {
  return TRADES.find(t => t.slug === slug);
}

export function getStateBySlug(slug: string): AusState | undefined {
  return STATES.find(s => s.slug === slug);
}

export function getHrcwBySlug(slug: string): HrcwCategory | undefined {
  return HRCW_CATEGORIES.find(c => c.slug === slug);
}
